# Generated by Django 5.0.2 on 2024-04-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascotasAPP', '0002_remove_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='Sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=10),
        ),
    ]
